
package com.og.cruses_MinFrame1.Views;

//import com.og.cruses_MinFrame1.Views.MainFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.WindowConstants;


/**
 *
 * @author acer
 */
public class Cruses_mono_hibrido extends javax.swing.JFrame {

    /**
     * Creates new form MianFrame2
     */
    public Cruses_mono_hibrido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Regresar_Primer_Panel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 380));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_Primer_Panel.setBackground(new java.awt.Color(255, 255, 255));
        Regresar_Primer_Panel.setForeground(new java.awt.Color(255, 255, 255));
        Regresar_Primer_Panel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\cruses_M\\src\\main\\java\\com\\og\\cruses_m\\icons\\cerrar-el-simbolo-de-la-cruz-en-un-circulo.png")); // NOI18N
        Regresar_Primer_Panel.setBorder(null);
        Regresar_Primer_Panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_Primer_PanelActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar_Primer_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255), java.awt.Color.black, new java.awt.Color(0, 0, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 255)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, 62));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar_Primer_PanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_Primer_PanelActionPerformed
        
      MainFrame primer_ventana= new MainFrame();
        primer_ventana.setVisible(true);
       primer_ventana.setLocationRelativeTo(null);                                                                                                                                                                                                                                                                                                                        
    //   primer_ventana.setDefaultCloseOperation(MainFrame.HIDE_ON_CLOSE);
  primer_ventana.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
     primer_ventana.addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent evt) {
          primer_ventana.dispose();
          //primer_ventana.dispatchEvent(evt);
          
      }
    });      
        

      
        
    }//GEN-LAST:event_Regresar_Primer_PanelActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar_Primer_Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
